name: Deploy Azure Function App

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Use Bun to install dependencies
        run: bun install

      - name: Build Typescript
        run: bun run build

      - name: Prepare Function ZIP
        run: bun run pack

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: azure-test-app
          package: ./azure-test.zip
          slot-name: stage

      - name: Logout from Azure
        run: az logout
